[[redirects]]
  from = "/downloads/latest.yml"
  to = "https://github.com/Guilhermesttt/Checkpoint---Launcher/releases/download/v3.2.2/latest.yml"
  status = 302
  force = true

[[redirects]]
  from = "/downloads/*"
  to = "https://github.com/Guilhermesttt/Checkpoint---Launcher/releases/download/v3.2.2/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "dist"
  command = "npm run build"