[[redirects]]
  from = "/downloads/latest.yml"
  to = "https://github.com/Guilhermesttt/Checkpoint---Launcher/releases/latest/download/latest.yml"
  status = 302
  force = true

[[redirects]]
  from = "/downloads/:filename"
  to = "https://github.com/Guilhermesttt/Checkpoint---Launcher/releases/latest/download/:filename"
  status = 302
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "dist"
  command = "npm run build"